INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (NEXTVAL('SEQ_ROL'), 'ADMIN');
INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (NEXTVAL('SEQ_ROL'), 'USER');

-- admin@admin / admin
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'admin@admin', '$2a$10$Tbt2mTwOerxIn396uy0x4eOKz3vXYqYQ.5Ntd7E5bkrklT7NIAiqi', 'Admin', 'Admin', 'Adminowo', '997998999', TRUE);
-- usr@usr / pass
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'usr@usr', '$2a$10$9EEK56M/YFFzWPMO35SyOusOTo.ldntvn1wKq5IvYZWaotBozbkXK', 'User', 'User', 'Userowo', '987654321', TRUE);
-- john@doe / pass
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'john@doe', '$2a$10$9EEK56M/YFFzWPMO35SyOusOTo.ldntvn1wKq5IvYZWaotBozbkXK', 'John', 'Doe', 'New York', '666555666', FALSE);

INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'ADMIN'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'usr@usr'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'john@doe'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));